// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { toast } from 'sonner';

const SUPABASE_URL = "https://iqilhrbsamcahdmklbnp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxaWxocmJzYW1jYWhkbWtsYm5wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4MDY1MDYsImV4cCI6MjA1ODM4MjUwNn0._dV7YSYkASLKnWljmPbtoai1kNG6hMe4GavPNt7no5E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      detectSessionInUrl: true,
      storage: window?.localStorage,
      storageKey: 'smartfield-auth',
      flowType: 'pkce'
    },
    global: {
      headers: {
        'x-client-info': 'smartfield-connect'
      }
    },
    realtime: {
      params: {
        eventsPerSecond: 10
      }
    }
  }
);

// Initialize Supabase connection
const initializeSupabase = async () => {
  try {
    // Check current session first
    const { data: { session }, error: sessionError } = await supabase.auth.getSession();
    if (sessionError) {
      console.error('Session check failed:', sessionError);
      return false;
    }

    if (session) {
      console.log('Active session found for user:', session.user.id);
      
      // Test the database connection with the active session
      const { count, error } = await supabase
        .from('profiles')
        .select('count', { count: 'exact' });

      if (error) {
        console.error('Database connection test failed:', error);
        toast.error('Erreur de connexion à la base de données');
        return false;
      }

      console.log('Database connection test successful. Profile count:', count);
    } else {
      console.log('No active session found - normal for non-authenticated users');
    }

    return true;
  } catch (err) {
    console.error('Failed to initialize Supabase:', err);
    toast.error('Erreur d\'initialisation de la connexion');
    return false;
  }
};

// Add event listeners for connection status
supabase.auth.onAuthStateChange((event, session) => {
  console.log('Auth state changed:', event);
  
  if (event === 'SIGNED_IN') {
    console.log('User signed in:', session?.user?.id);
    toast.success('Connexion réussie');
  } else if (event === 'SIGNED_OUT') {
    console.log('User signed out');
    localStorage.removeItem('smartfield-auth');
    window.location.href = '/login';
  } else if (event === 'TOKEN_REFRESHED') {
    console.log('Session token refreshed');
  }
});

// Initialize connection
initializeSupabase().then(success => {
  if (!success) {
    console.error('Failed to initialize Supabase connection');
    toast.error('Erreur de connexion au service');
  }
});
